config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  mount Ckeditor::Engine => "/ckeditor"
  root "pages#home"
  get "pages/home"
  get "pages/about"
  get "pages/help"
  get "/signup",  to: "users#new"
  get "/login",   to: "sessions#new"
  get :index, controller: :searchs
  post "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: [:index]
  resources :post_reviews, except: [:index] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :bookings, only: [:index, :create, :destroy]
  resources :films, only: [:show]
  resources :ratings, only: [:create, :update, :destroy]
  resources :requests

  namespace :admin do
    root "admin#index"
    resources :films
    resources :post_reviews, except: [:show]
    resources :users, only: [:index, :destroy]
    resources :bookings, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :requests, only: [:index, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_review
  scope :desc_create_at, -> {order("created_at desc")}
  validates :content, presence: true
  
  def self.new_comments
    where("created_at > ?", Time.new.beginning_of_day)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  def index
    @comments = Comment.desc_create_at.paginate page: params[:page],
      per_page: Settings.paginate_number.per_page
  end

  def destroy
    @comment = Comment.find_by id: params[:id]
    if @comment.destroy
      flash[:success] = t "flash.destroy_comment_success"
    else
      flash[:danger] = t "flash.destroy_comment_failed"
    end
    redirect_to admin_comments_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_post_review

  def create
    @comment = @post_review.comments.build comment_params
    @comment.user = current_user
    if @comment.save
      @comments = @post_review.comments.desc_create_at.paginate page: params[:page],
        per_page: Settings.paginate_number.per_page
      render json: {
        status: :success,
        content: render_to_string(partial: "comment/comment",
          locals: {comments: @comments})
      }
    else
      render json: {
        status: :error
      }
    end
  end

  def destroy
    @comment = Comment.find_by id: params[:id]
    if @comment.destroy
      @comments = @post_review.comments.desc_create_at.paginate page: params[:page],
        per_page: Settings.paginate_number.per_page
      render json: {
        status: :success,
        content: render_to_string(partial: "comment/comment",
          locals: {comments: @comments})
      }
    else
      render json: {
        status: :error
      }
    end
  end

  private

  def comment_params
    params.require(:comments).permit(:content, :post_review_id)
  end

  def load_post_review
    @post_review = PostReview.find_by id: params[:post_review_id]
  end
end

app/views/admin/comments/_comment.html.erb
<tr>
  <td><%= link_to comment.user.name, user_path(comment.user) %></td>
  <td><%= link_to comment.post_review.title,
    post_review_path(comment.post_review) %></td>
  <td><%= comment.content %></td>
  <td>
    <%= link_to t(".delete"), admin_comment_path(comment), method: :delete %>
  </td>
</tr>

app/views/admin/comments/index.html.erb
<div class="row">
  <h2 class="sub-header"><%= t ".comment_list" %></h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t ".name" %></th>
          <th><%= t ".post_review" %></th>
          <th><%= t ".content" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "comment", collection: @comments %>
      </tbody>
    </table>
    <%= will_paginate @comments %>
  </div>
</div>