config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  mount Ckeditor::Engine => "/ckeditor"
  root "pages#home"
  get "pages/home"
  get "pages/about"
  get "pages/help"
  get "/signup",  to: "users#new"
  get "/login",   to: "sessions#new"
  get :index, controller: :searchs
  post "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: [:index]
  resources :post_reviews, except: [:index] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :bookings, only: [:index, :create, :destroy]
  resources :films, only: [:show]
  resources :ratings, only: [:create, :update, :destroy]
  resources :requests

  namespace :admin do
    root "admin#index"
    resources :films
    resources :post_reviews, except: [:show]
    resources :users, only: [:index, :destroy]
    resources :bookings, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :requests, only: [:index, :destroy]
  end
end

app/views/shared/_booking.html.erb
<tr id ="booking-<%= booking.id %>">
  <td><%= booking.watching_time.watching_day.film.name %></td>
  <td><%= booking.watching_time.watching_day.day_watching %></td>
  <td><%= booking.watching_time.time.to_formatted_s :time %></td>
  <td><%= booking.quantity %></td>
  <td>
    <%= link_to t(".cancellation"), "#",
      class: "cancellation-booking", id: booking.id %>
  </td>
</tr>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize @user.errors.count, t("share.error_messages.error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_index.html.erb
<div class="container container-fluid">
  <div class="row">
    <h2 class="sub-header"><%= t ".my_post_list" %></h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t ".title" %></th>
            <th><%= t ".approve" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "shared/post", collection: @posts %>
        </tbody>
      </table>
      <%= will_paginate @posts %>
    </div>
  </div>
</div>

app/views/shared/_post.html.erb
<tr>
  <td><%= link_to post.title, post_review_path(post) %></td>
  <td>
    <% if post.approve %><%= t ".approve_true" %>
      <% else %> <%= t ".approve_fail" %>
    <% end %>
  </td>
  <td><%= link_to t(".delete"), post_review_path(post), method: :delete, data: {confirm: t(".you_sure")} %>
  </td>
  <td><%= link_to t(".edit_post"), edit_post_review_path(post) %></td>
</tr>

app/views/shared/_posts_home.html.erb
<div class="container">
  <h2><%= t ".booking_online" %></h2>
  <div class="row">
    <% @posts.each do |film| %>
    <li class="col-sm-3">

      <div class="container carousel-inner">
        <div class="col-md-3">
          <h3><%= film.title %></h3>
          <%= image_tag film.image %>
          <p><%= film.content %></p>
        </div>
      </div>
      </li>
    <% end %>
  </div>
</div>

app/views/shared/_request_form.html.erb
<%= form_for(@request) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :title, t("users.form.title") %>
  <%= f.text_field :title, class: "form-control", placeholder: t("users.form.fill_title") %></br>
  <%= f.label :content, t("users.form.content") %>
  <%= f.cktext_area :content, class: "form-control" %>
  <%= f.submit t("users.form.submit"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_share_facebook_button.html.erb
<div class="fb-share-button" data-href="<%= request.url %>"
  data-layout="button_count" data-size="small"
  data-mobile-iframe="true">
  <a class="fb-xfbml-parse-ignore" target="_blank"
    href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a>
</div>