config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  mount Ckeditor::Engine => "/ckeditor"
  root "pages#home"
  get "pages/home"
  get "pages/about"
  get "pages/help"
  get "/signup",  to: "users#new"
  get "/login",   to: "sessions#new"
  get :index, controller: :searchs
  post "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: [:index]
  resources :post_reviews, except: [:index] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :bookings, only: [:index, :create, :destroy]
  resources :films, only: [:show]
  resources :ratings, only: [:create, :update, :destroy]
  resources :requests

  namespace :admin do
    root "admin#index"
    resources :films
    resources :post_reviews, except: [:show]
    resources :users, only: [:index, :destroy]
    resources :bookings, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :requests, only: [:index, :destroy]
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
    @posts = PostReview.approved.ransack(title_cont: params[:q]).result(distinct: true)
    @films = Film.ransack(name_cont: params[:q]).result(distinct: true)

    respond_to do |format|
      format.html {}
      format.json {
        @films = @films.limit(4)
        @posts = @posts.limit(4)
      }
    end
  end
end

app/views/searchs/index.html.erb
<div class="row">
  <div class="col">
    <h1><%= t "users.search.film" %></h1>
    <% @films.each do |film| %>
    <div class="row set-border">
        <div class="col-md-4 col-remove-padding-left">
      <%= image_tag film.image %>
      </div>
      <p><%= link_to film.name, film_path(film) %></p>
      <p><%= film.describe.truncate(Settings.film.describe_minimum,
          separator: " ") %></p>
      </div>
    <% end %>
  </div>
  <div class="col">
    <h1><%= t "users.search.post" %></h1>
    <% @posts.each do |post| %>
      <div class="row set-border">
        <div class="col-md-4 col-remove-padding-left">
          <%= image_tag post.image %>
        </div>
        <p><%= link_to post.title, post_review_path(post) %></p>
      </div>
    <% end %>
  </div>
</div>
<p><%= link_to t("layouts.search.request"), new_request_path %></p>

app/views/searchs/search.html.erb
<div class="row">
  <div class="col">
    <h1>Films</h1>
    <% @films.each do |film| %>
      <p><%= link_to film.name, film_path(film) %></p>
    <% end %>
  </div>

  <div class="col">
    <h1>Posts</h1>
    <% @posts.each do |post| %>
      <p><%= link_to post.title, post_review_path(post) %></p>
    <% end %>
  </div>
</div>